services:
  frontend:
    build:
      target: dev
    volumes:
      - ./src/frontend/src:/app/src:cached
      - frontend_node_modules:/app/node_modules

  api:
    build:
      target: dev
    volumes:
      - ./src/api:/app:cached
      - api_node_modules:/app/node_modules

volumes:
  frontend_node_modules:
  api_node_modules: